apiVersion: v1
kind: Secret
metadata:
  name: pccs-tls
  labels:
    {{- include "pccs.labels" . | nindent 4 }}
type: Opaque
data:
  file.crt: {{ .Values.pccsTlsKeyPair.certificate | b64enc | quote }}
  private.pem: {{ .Values.pccsTlsKeyPair.privateKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pccs-config
  labels:
    {{- include "pccs.labels" . | nindent 4 }}
type: Opaque
data:
  default.json: {{ tpl (.Files.Get "config/default.json") . | b64enc | quote }}
